version: '2'
services:
  cni-driver:
    privileged: true
    image: registry.cn-hangzhou.aliyuncs.com/ljchen/rancher-cni-driver:v0.2
    command: /bin/sh -c "while true; do modprobe ebtables; echo -e 'CNI_CATTLE_IPADDR='$CNI_CATTLE_IPADDR > /opt/cni/conf; sleep 60; done"
    network_mode: host
    volumes:
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /var/hfbank:/opt/cni/hfbank
    pid: host
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent_service.hfflat: 'true'
      io.rancher.network.cni.binary: 'rancher-cni-bridge'
      io.rancher.container.dns: 'true'
